### PR TITLE
Update Weathermap to work with modern LibreNMS

### PR DESCRIPTION
**Pull request by murrant**
Fixes:
 * duplicate class name
 * issues with paths
 * direct use of DB credentials and direct DB access
 * map-poller.php doesn't need to boot LibreNMS, it only needs the config
 * use $librenms_base from config.inc.php and define it better there.
 * apparently trailing whitespace removal because my editor doesn't like it :D

### CODE REVIEW

**Comment by boudreau** [comment]
Hi,

looks like this pull request working with my release.

**Comment by DonovanEsterhuizen** [comment]
@boudreau how do I pull this request bit of a newbie

**Comment by DonovanEsterhuizen** [comment]
root@nms:/opt/librenms/html/plugins/Weathermap# git pull https://github.com/librenms-plugins/Weathermap.git

Is the above correct?

**Comment by boudreau** [comment]
first clone the repo:  
`git clone  https://github.com/librenms-plugins/Weathermap.git`

Go in the directory and get the pull request #60 :
`git fetch origin pull/60/head:test`

Called the branch "test"

and then activate the branch
`git checkout test`


The pull request has been merge now, so no need , but for futur ref.

**Pull request merged**
